### ISSUE TITLE
Multiple identical wallets.  Result of failure to fetch outputs?

### ISSUE THREAD

**Issue by scoobybejesus** [mymonero/mymonero-app-ios#57]
I was trying to make a transfer on or about May 3, 2018.  Others were reporting similar inability to send, receiving "Failure to fetch outputs."  I tried several times to send.  

Probably not relevant, but I think the first time I tried to send I accidentally didn't change the fee from medium to low.  I was working at the time, so not paying close attention.  When I hit the home button for the phone to wake up and entered my PIN, it hadn't sent.  I was relieved, adjusted the fee down, entered the amount and address, and sent again.

Again, I was working, so I missed the time out.  I tried again and missed the time out.  As I remember it, I tried once more (a fourth time), this time being sure to tap on the screen, to make sure there the screen turning off had nothing to do with it (apparently, the screen will stay awake for the duration of a spend operation), and I finally saw the failure to fetch outputs message.

Anyway, maybe I did try to send one more time, because now, a week later, I opened the app, and I have six identical versions of my wallet.  I can open them up on the main wallet page, and they all reflect the same activity.  When I go to the send page, I can select any of them.  When I send, the amount is deducted from all of them.

Here's a pic.

![image-1-2](https://user-images.githubusercontent.com/21372487/39880797-ce61f4c8-544c-11e8-8917-34f710fc4164.jpg)

After those failures, I think I just did a home button double click and swipe up to close the app.  Now I have six wallets.  I used Testflight to update to the latest version.  The wallets remain.  

I tried to create a transaction while the phone was in airplane mode, in hopes I could reproduce, but it knows there's no internet connection and won't even try.

**Comment by paulshapiro** [comment]
just fyi, the app ought to be keeping itself awake while sending - if that's not happening, it's an additional bug
