### ISSUE TITLE
"From" selector on "Send Monero" screen should also show the balance in the currency chosen for sending 

### ISSUE THREAD

**Issue by mikethetike** [mymonero/mymonero-app-ios#80]
I really like the feature that you can choose to send an amount in a different currency, e.g. USD, but it would be nice if it displayed the available funds in the "From" wallet in that currency as well as XMR

**Comment by paulshapiro** [comment]
Hey there. Thanks for the issue. You can get this to happen by changing the display ccy under Preferences.

**Comment by mikethetike** [comment]
Thanks. It would be nice to see both the default currency and the XMR value

**Comment by paulshapiro** [comment]
ok, noted
