### ISSUE TITLE
App crashes with self-hosted API

### ISSUE THREAD

**Issue by dzonatan** [mymonero/mymonero-app-ios#90]
The application crashes when using with a self-hosted api ([monero-lws](https://github.com/vtnerd/monero-lws) in my case).
Strangely, this happens ONLY when wallet has some balance in it.  
There are no issues with freshly (0 balance) created wallets.

iOS v14.4

**Comment by dzonatan** [comment]
After some debugging I've found that `monero-lws` uses slightly different timestamp format that cannot be parsed by mymonero-ios which leads to this crash.
However, I'm not sure which side should have to change the format as both uses different variation than [specified in lightwallet API](https://github.com/monero-project/meta/blob/master/api/lightwallet_rest.md#get_address_txs). I think I'll have to raise this question on meta project as the specification itself is a bit too vague and needs a better explanation.

Still, I think this needs to be handled in a better way, e.g. tell the user that server didn't respond with correct data or something like that... so I'll keep this issue open.

**Comment by devinpearson** [comment]
Hi @dzonatan, monero-lws has updated their dates to match the mymonero app , can you confirm if this is still an issue?

**Comment by dzonatan** [comment]
Yes - it's working as expected now.
Although, I still think that the error handler could be improved in case something similar breaks in the future.
But feel free to close it.

**Comment by devinpearson** [comment]
Definitely agree with the need for better error handling for it. I will be creating an enhancement issue in our desktop repo which will be extended to the ios and Android app
